# Generated by Django 5.2.8 on 2025-11-13 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveIndex(
            model_name='networknode',
            name='electronics_node_ty_c3cdd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='networknode',
            name='electronics_level_f4f8ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='networknode',
            name='electronics_created_b1d2f5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networknode', to='electronics.contact', verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(related_name='network_nodes', to='electronics.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
